name: Build and Upload JAR on Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openjdk:17-slim

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'iyubondyrev/correct_script.server'
          path: 'correct_script.server'

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Sever Jar
        run: ./gradlew BuildServerJar
        working-directory: ./correct_script.server


      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./correct_script.server/build/libs/Server.jar
          asset_name: correct_script.server.jar
          asset_content_type: application/java-archive

      - name: Upload config example to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./correct_script.server/src/main/resources/application.yaml
          asset_name: config.yaml
          asset_content_type: application/x-yaml


      - name: Upload initial prompt example to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./correct_script.server/src/main/resources/initial_prompt.txt
          asset_name: initial_prompt.txt
          asset_content_type: text/plain

      - name: Upload run script to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./correct_script.server/correct_script-server.sh
          asset_name: correct_script-server.sh
          asset_content_type: text/plain
